/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fpatkXHlHVd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import Link from "next/link";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { ExpandIcon } from "lucide-react";
import TaskCard from "./TaskCard";
import SideBar from "./SideBar";
import ThemeButton from "./buttons/ThemeButton";
import UserButton from "./buttons/UserButton";

export function Dashboard() {
  return (
    <div className="flex h-screen flex-col">
      <header className="bg-white border-b p-4">
        <div className="flex items-center justify-between">
          <div className="text-2xl font-bold">Connetiz</div>
          <div className="flex items-center space-x-4">
            <ThemeButton />
            <UserButton />
          </div>
        </div>
      </header>
      <div className="flex h-full">
        <SideBar /> {/* The dashboard's sidebar */}
        <main className="flex-1 p-8">
          <div className="flex items-center justify-between">
            <div>
              <nav className="text-sm text-gray-500">
                <Link href="#" className="hover:underline" prefetch={false}>
                  Dashboard
                </Link>
                &gt;{" "}
                <Link href="#" className="hover:underline" prefetch={false}>
                  Kanban
                </Link>
              </nav>
              <h1 className="text-2xl font-bold">Kanban</h1>
              <p className="text-gray-500">Manage tasks by dnd</p>
            </div>
            <Button variant="outline" className="h-10">
              + Add New Todo
            </Button>
          </div>
          <div className="flex mt-8 space-x-4">
            <TaskCard /> {/* This component is the task card */}
            <Button variant="outline" className="h-10">
              + Add New Section
            </Button>
          </div>
        </main>
      </div>
    </div>
  );
}
